// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoMGjbMl3fFdZ0g6C2SnQiRtwj5KbdR7s',
    appId: '1:1007239374066:web:c6295cc1b98a9e8ea01c6b',
    messagingSenderId: '1007239374066',
    projectId: 'app-ando',
    authDomain: 'app-ando.firebaseapp.com',
    storageBucket: 'app-ando.firebasestorage.app',
    measurementId: 'G-N8DYT22CZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf-tp5-opoXJSADXkBeB31DMBdqRyEb0U',
    appId: '1:364283556136:android:9c8f501a3997e22a9ce01d',
    messagingSenderId: '364283556136',
    projectId: 'app-ando-auronix',
    storageBucket: 'app-ando-auronix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxhwfxMh09ifEVCiPoa5rfUpMppjDx8Qo',
    appId: '1:364283556136:ios:c5604bdaece7ba829ce01d',
    messagingSenderId: '364283556136',
    projectId: 'app-ando-auronix',
    storageBucket: 'app-ando-auronix.firebasestorage.app',
    iosBundleId: 'com.package.appauronix2026',
  );
}
